"""Career knowledge base: the 9 careers, certification catalogue, skill labels and soft-skill pillars."""

import json
import os
from typing import Any, Dict, List

from src.paths import DATA_DIR


CAREER_UNIVERSE = {
    "Software Engineer": {
        "title": "Software Engineer",
        "archetype": "Engineering & Architecture",
        "category": "Core Engineering",
        "description": "Architects scalable software systems, backend microservices, robust APIs, and enterprise applications.",
        "role_dynamic": "Requires sustained concentration on complex abstractions and anticipating edge cases.",
        "icon": "💻",
        "work_style_fit": "Technical Specialist",
        "required_soft_skills": [
            "Problem Solving & Logic",
            "Debugging & Root-Cause Analysis",
            "Detail-Oriented & Precision",
            "Innovation & Prototyping",
        ],
        "weight_bonus": 0.20,
        "benchmark_skills": {
            "DSA": 85,
            "OOP": 85,
            "DBMS": 75,
            "OS_Networks": 75,
            "SE_Principles": 85,
            "Math_Stats": 70,
            "Python": 3.5,
            "Java_CPP": 4.0,
            "SQL": 3.5,
            "WebStack": 4.0,
            "CloudDocker": 3.0,
            "ML_AI": 2.0,
            "MobileDev": 2.5,
            "Cybersecurity": 2.5,
        },
        "target_workstyles": ["Technical Specialist", "R&D / Creative"],
    },
    "Data Scientist": {
        "title": "Data Scientist",
        "archetype": "Data & Analytics",
        "category": "Analytics & Intelligence",
        "description": "Transforms high-dimensional datasets into predictive statistical models and strategic business insights.",
        "role_dynamic": "Translating messy raw data and business rules into actionable executive decisions.",
        "icon": "📊",
        "work_style_fit": "R&D / Creative",
        "required_soft_skills": [
            "Analytical & Critical Thinking",
            "Storytelling & Conceptualizing",
            "Detail-Oriented & Precision",
            "Quantitative & Mathematical",
            "Research & Investigation",
        ],
        "weight_bonus": 0.20,
        "benchmark_skills": {
            "DSA": 75,
            "OOP": 70,
            "DBMS": 85,
            "OS_Networks": 65,
            "SE_Principles": 70,
            "Math_Stats": 90,
            "Python": 4.5,
            "Java_CPP": 2.5,
            "SQL": 4.5,
            "WebStack": 2.0,
            "CloudDocker": 3.0,
            "ML_AI": 4.5,
            "MobileDev": 1.5,
            "Cybersecurity": 2.0,
        },
        "target_workstyles": ["R&D / Creative", "Consulting / Management"],
    },
    "AI Engineer": {
        "title": "AI Engineer",
        "archetype": "Engineering & Architecture",
        "category": "Artificial Intelligence",
        "description": "Develops deep learning architectures, neural networks, foundation model pipelines, and autonomous agent systems.",
        "role_dynamic": "Sustained concentration on multi-dimensional neural abstractions, model alignment, and anticipating failure modes.",
        "icon": "🧠",
        "work_style_fit": "R&D / Creative",
        "required_soft_skills": [
            "Problem Solving & Logic",
            "Innovation & Prototyping",
            "Research & Investigation",
            "Quantitative & Mathematical",
        ],
        "weight_bonus": 0.20,
        "benchmark_skills": {
            "DSA": 85,
            "OOP": 80,
            "DBMS": 75,
            "OS_Networks": 70,
            "SE_Principles": 80,
            "Math_Stats": 90,
            "Python": 5.0,
            "Java_CPP": 3.5,
            "SQL": 3.5,
            "WebStack": 2.5,
            "CloudDocker": 4.0,
            "ML_AI": 5.0,
            "MobileDev": 2.0,
            "Cybersecurity": 2.5,
        },
        "target_workstyles": ["R&D / Creative", "Technical Specialist"],
    },
    "Cloud Architect": {
        "title": "Cloud Architect",
        "archetype": "Infrastructure, Systems & Security",
        "category": "Cloud Infrastructure",
        "description": "Designs highly-available distributed systems, multi-cloud topologies, container orchestration, and CI/CD pipelines.",
        "role_dynamic": "Rapid diagnosis, fault-tolerant topology modeling, and incident escalation under pressure.",
        "icon": "☁️",
        "work_style_fit": "Technical Specialist",
        "required_soft_skills": [
            "Hardware & System Troubleshooting",
            "Planning & Task Organizing",
            "Working Under Pressure / Incidents",
            "Problem Solving & Logic",
        ],
        "weight_bonus": 0.20,
        "benchmark_skills": {
            "DSA": 70,
            "OOP": 70,
            "DBMS": 80,
            "OS_Networks": 90,
            "SE_Principles": 80,
            "Math_Stats": 65,
            "Python": 3.5,
            "Java_CPP": 3.0,
            "SQL": 3.5,
            "WebStack": 3.0,
            "CloudDocker": 5.0,
            "ML_AI": 2.0,
            "MobileDev": 2.0,
            "Cybersecurity": 4.0,
        },
        "target_workstyles": ["Technical Specialist", "Consulting / Management"],
    },
    "UX Designer": {
        "title": "UX Designer",
        "archetype": "Creative, UI/UX & Media",
        "category": "Product & Design",
        "description": "Conducts user research, cognitive ergonomics evaluation, and crafts design systems for delightful user journeys.",
        "role_dynamic": "Balancing aesthetic appeal with cognitive ergonomics, user empathy, and usability constraints.",
        "icon": "🎨",
        "work_style_fit": "R&D / Creative",
        "required_soft_skills": [
            "Active Listening & Empathy",
            "Creative & Visual Design",
            "Storytelling & Conceptualizing",
            "Innovation & Prototyping",
        ],
        "weight_bonus": 0.20,
        "benchmark_skills": {
            "DSA": 50,
            "OOP": 55,
            "DBMS": 50,
            "OS_Networks": 45,
            "SE_Principles": 80,
            "Math_Stats": 55,
            "Python": 2.0,
            "Java_CPP": 1.5,
            "SQL": 2.0,
            "WebStack": 4.0,
            "CloudDocker": 1.5,
            "ML_AI": 2.0,
            "MobileDev": 3.5,
            "Cybersecurity": 1.5,
        },
        "target_workstyles": ["R&D / Creative", "Consulting / Management"],
    },
    "IT Business Analyst": {
        "title": "IT Business Analyst",
        "archetype": "Management & Consulting",
        "category": "Business & Strategy",
        "description": "Synthesizes stakeholder requirements, functional specifications, Agile user stories, and digital transformation initiatives.",
        "role_dynamic": "Keeping cross-functional teams aligned, managing client expectations, and negotiating scope.",
        "icon": "📈",
        "work_style_fit": "Consulting / Management",
        "required_soft_skills": [
            "Communicating & Articulating",
            "Analytical & Critical Thinking",
            "Planning & Task Organizing",
            "Negotiation & Persuasion",
            "Active Listening & Empathy",
        ],
        "weight_bonus": 0.20,
        "benchmark_skills": {
            "DSA": 55,
            "OOP": 55,
            "DBMS": 75,
            "OS_Networks": 60,
            "SE_Principles": 90,
            "Math_Stats": 75,
            "Python": 2.5,
            "Java_CPP": 2.0,
            "SQL": 4.0,
            "WebStack": 2.5,
            "CloudDocker": 2.0,
            "ML_AI": 2.5,
            "MobileDev": 2.0,
            "Cybersecurity": 2.5,
        },
        "target_workstyles": ["Consulting / Management"],
    },
    "Game Developer": {
        "title": "Game Developer",
        "archetype": "Creative, UI/UX & Media",
        "category": "Interactive Media",
        "description": "Engineers real-time 2D/3D gameplay mechanics, custom graphics shaders, physics engines, and virtual simulations.",
        "role_dynamic": "Balancing visual aesthetic feel with rigorous real-time algorithmic physics constraints.",
        "icon": "🎮",
        "work_style_fit": "Technical Specialist",
        "required_soft_skills": [
            "Creative & Visual Design",
            "Problem Solving & Logic",
            "Hands-on Prototyping",
            "Storytelling & Conceptualizing",
        ],
        "weight_bonus": 0.20,
        "benchmark_skills": {
            "DSA": 85,
            "OOP": 90,
            "DBMS": 60,
            "OS_Networks": 70,
            "SE_Principles": 75,
            "Math_Stats": 85,
            "Python": 3.0,
            "Java_CPP": 5.0,
            "SQL": 2.5,
            "WebStack": 2.5,
            "CloudDocker": 2.5,
            "ML_AI": 2.5,
            "MobileDev": 3.5,
            "Cybersecurity": 2.0,
        },
        "target_workstyles": ["Technical Specialist", "R&D / Creative"],
    },
    "CAD-CAM Engineer": {
        "title": "CAD-CAM Engineer",
        "archetype": "Engineering & Architecture",
        "category": "Computational Manufacturing",
        "description": "Applies parametric geometric modeling, finite element analysis, and automated numerical manufacturing systems.",
        "role_dynamic": "High methodical precision, mathematical spatial reasoning, and manufacturing tolerances.",
        "icon": "📐",
        "work_style_fit": "Technical Specialist",
        "required_soft_skills": [
            "Detail-Oriented & Precision",
            "Problem Solving & Logic",
            "Hands-on Prototyping",
            "Quantitative & Mathematical",
        ],
        "weight_bonus": 0.20,
        "benchmark_skills": {
            "DSA": 70,
            "OOP": 70,
            "DBMS": 60,
            "OS_Networks": 60,
            "SE_Principles": 75,
            "Math_Stats": 85,
            "Python": 3.0,
            "Java_CPP": 3.5,
            "SQL": 2.5,
            "WebStack": 2.0,
            "CloudDocker": 2.0,
            "ML_AI": 2.5,
            "MobileDev": 1.5,
            "Cybersecurity": 2.0,
        },
        "target_workstyles": ["Technical Specialist"],
    },
    "Cybersecurity Specialist": {
        "title": "Cybersecurity Specialist",
        "archetype": "Infrastructure, Systems & Security",
        "category": "Information Security",
        "description": "Performs threat hunting, security auditing, vulnerability assessment, cryptography deployment, and incident defense.",
        "role_dynamic": "Rapid diagnosis, methodical protocol precision, and calm decision making during live security breaches.",
        "icon": "🛡️",
        "work_style_fit": "Technical Specialist",
        "required_soft_skills": [
            "Working Under Pressure / Incidents",
            "Debugging & Root-Cause Analysis",
            "Process & Protocol Adherence",
            "Analytical & Critical Thinking",
        ],
        "weight_bonus": 0.20,
        "benchmark_skills": {
            "DSA": 75,
            "OOP": 70,
            "DBMS": 75,
            "OS_Networks": 95,
            "SE_Principles": 75,
            "Math_Stats": 75,
            "Python": 4.0,
            "Java_CPP": 3.5,
            "SQL": 3.5,
            "WebStack": 3.0,
            "CloudDocker": 4.0,
            "ML_AI": 2.5,
            "MobileDev": 2.0,
            "Cybersecurity": 5.0,
        },
        "target_workstyles": ["Technical Specialist", "Consulting / Management"],
    },
}


# Industry Certification Catalogue with Skill Tags for Vector Matching
def load_certification_catalog() -> List[Dict[str, Any]]:
    """Loads certification database from certifications.json with fallback."""
    json_path = os.path.join(DATA_DIR, "certifications.json")
    if os.path.exists(json_path):
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return [
        {
            "id": "meta-frontend",
            "title": "Meta Front-End Developer Professional Certificate",
            "issuer": "Coursera / Meta",
            "level": "Beginner to Intermediate",
            "target_years": ["1st Year", "2nd Year", "3rd Year"],
            "domains": ["Software Engineering", "Web Development", "UI/UX Design"],
            "skills": ["Modern Web Stack", "Software Engineering Principles", "Mobile Development"],
            "skill_keys": ["WebStack", "SE_Principles", "MobileDev"],
            "vector": {"WebStack": 1.0, "SE_Principles": 0.7, "MobileDev": 0.5},
            "description": "Master React, JavaScript ES6+, HTML5/CSS3, responsive UI frameworks, and production-grade web application architecture.",
            "official_url": "https://www.coursera.org/professional-certificates/meta-front-end-developer",
            "prep_url": "https://www.metacareers.com/career-programs/certificates",
            "exam_guide_url": "https://www.metacareers.com/career-programs/certificates"
        },
        {
            "id": "aws-dev-assoc",
            "title": "AWS Certified Developer – Associate (DVA-C02)",
            "issuer": "Amazon Web Services",
            "level": "Intermediate",
            "target_years": ["2nd Year", "3rd Year", "4th Year"],
            "domains": ["Software Engineering", "Cloud & DevOps", "Web Development"],
            "skills": ["Modern Web Stack", "Cloud Architecture & Docker", "Software Engineering Principles"],
            "skill_keys": ["WebStack", "CloudDocker", "SE_Principles"],
            "vector": {"CloudDocker": 1.0, "WebStack": 0.85, "SE_Principles": 0.75},
            "description": "Validates cloud-native application development, serverless AWS Lambda, DynamoDB, API Gateways, container deployment, and CI/CD pipelines.",
            "official_url": "https://aws.amazon.com/certification/certified-developer-associate/",
            "prep_url": "https://aws.amazon.com/training/digital/",
            "exam_guide_url": "https://d1.awsstatic.com/training-and-certification/docs-dev-associate/AWS-Certified-Developer-Associate_Exam-Guide.pdf"
        },
        {
            "id": "meta-backend",
            "title": "Meta Back-End Developer Professional Certificate",
            "issuer": "Coursera / Meta",
            "level": "Intermediate",
            "target_years": ["2nd Year", "3rd Year", "4th Year"],
            "domains": ["Software Engineering", "Web Development", "Cloud & DevOps"],
            "skills": ["Modern Web Stack", "Python Programming", "SQL & Relational Querying", "Database Management Systems"],
            "skill_keys": ["WebStack", "Python", "SQL", "DBMS"],
            "vector": {"WebStack": 0.95, "Python": 0.9, "SQL": 0.85, "DBMS": 0.8},
            "description": "Comprehensive back-end APIs, Django, REST microservices, relational database modeling, Linux servers, and cloud containerization.",
            "official_url": "https://www.coursera.org/professional-certificates/meta-back-end-developer",
            "prep_url": "https://www.coursera.org/professional-certificates/meta-back-end-developer",
            "exam_guide_url": "https://www.metacareers.com/career-programs/certificates"
        },
        {
            "id": "fcc-fullstack",
            "title": "freeCodeCamp Full-Stack Developer Path",
            "issuer": "freeCodeCamp",
            "level": "Beginner to Intermediate",
            "target_years": ["1st Year", "2nd Year", "3rd Year"],
            "domains": ["Software Engineering", "Web Development"],
            "skills": ["Modern Web Stack", "Data Structures & Algorithms", "SQL & Relational Querying"],
            "skill_keys": ["WebStack", "DSA", "SQL"],
            "vector": {"WebStack": 1.0, "DSA": 0.75, "SQL": 0.65},
            "description": "300+ hours of verified project-based builds in Responsive Web Design, JavaScript Algorithms, Front-End Libraries, and Node.js APIs.",
            "official_url": "https://www.freecodecamp.org/learn/",
            "prep_url": "https://www.freecodecamp.org/learn/",
            "exam_guide_url": "https://www.freecodecamp.org/learn/"
        },
        {
            "id": "oracle-java-assoc",
            "title": "Oracle Certified Associate: Java SE Programmer (1Z0-808)",
            "issuer": "Oracle Corporation",
            "level": "Intermediate",
            "target_years": ["2nd Year", "3rd Year", "4th Year"],
            "domains": ["Software Engineering", "Core Systems"],
            "skills": ["Java / C++ Systems", "Object-Oriented Programming", "Data Structures & Algorithms"],
            "skill_keys": ["Java_CPP", "OOP", "DSA"],
            "vector": {"Java_CPP": 1.0, "OOP": 0.95, "DSA": 0.75},
            "description": "Validates rigorous core Java programming, object-oriented encapsulation, exception handling, collections, and algorithmic fluency.",
            "official_url": "https://education.oracle.com/oracle-certified-associate-java-se-8-programmer/trackp_333",
            "prep_url": "https://mylearn.oracle.com/ou/learning-path/java-explorer/79708",
            "exam_guide_url": "https://education.oracle.com/java-se-8-programmer-i/pexam_1Z0-808"
        },
        {
            "id": "aws-solutions-architect",
            "title": "AWS Certified Solutions Architect – Associate (SAA-C03)",
            "issuer": "Amazon Web Services",
            "level": "Intermediate to Advanced",
            "target_years": ["3rd Year", "4th Year"],
            "domains": ["Cloud & DevOps", "Infrastructure & Networking", "Software Engineering", "Cybersecurity & Defense"],
            "skills": ["Cloud Architecture & Docker", "OS & Computer Networks", "Cybersecurity Defense", "Software Engineering Principles"],
            "skill_keys": ["CloudDocker", "OS_Networks", "Cybersecurity", "SE_Principles"],
            "vector": {"CloudDocker": 1.0, "OS_Networks": 0.85, "Cybersecurity": 0.65, "SE_Principles": 0.65},
            "description": "Industry benchmark for designing resilient, high-performing, cost-optimized, and secure multi-tier distributed cloud architectures.",
            "official_url": "https://aws.amazon.com/certification/certified-solutions-architect-associate/",
            "prep_url": "https://aws.amazon.com/training/digital/",
            "exam_guide_url": "https://d1.awsstatic.com/training-and-certification/docs-sa-assoc/AWS-Certified-Solutions-Architect-Associate_Exam-Guide.pdf"
        },
        {
            "id": "aws-cloud-practitioner",
            "title": "AWS Certified Cloud Practitioner (CLF-C02)",
            "issuer": "Amazon Web Services",
            "level": "Foundational",
            "target_years": ["1st Year", "2nd Year"],
            "domains": ["Cloud & DevOps", "Software Engineering", "Infrastructure & Networking"],
            "skills": ["Cloud Architecture & Docker", "OS & Computer Networks"],
            "skill_keys": ["CloudDocker", "OS_Networks"],
            "vector": {"CloudDocker": 0.85, "OS_Networks": 0.55},
            "description": "Foundational understanding of high-level AWS cloud concepts, security models, core compute services, and billing fundamentals.",
            "official_url": "https://aws.amazon.com/certification/certified-cloud-practitioner/",
            "prep_url": "https://aws.amazon.com/training/digital/",
            "exam_guide_url": "https://d1.awsstatic.com/training-and-certification/docs-cloud-practitioner/AWS-Certified-Cloud-Practitioner_Exam-Guide.pdf"
        },
        {
            "id": "gcp-data-engineer",
            "title": "Google Cloud Professional Data Engineer",
            "issuer": "Google Cloud",
            "level": "Professional",
            "target_years": ["3rd Year", "4th Year"],
            "domains": ["Data & Analytics", "Artificial Intelligence", "Database & Big Data", "Cloud & DevOps"],
            "skills": ["SQL & Relational Querying", "Cloud Architecture & Docker", "Python Programming", "Machine Learning & AI", "Database Management Systems"],
            "skill_keys": ["SQL", "CloudDocker", "Python", "ML_AI", "DBMS"],
            "vector": {"SQL": 1.0, "CloudDocker": 0.85, "Python": 0.75, "ML_AI": 0.75, "DBMS": 0.85},
            "description": "Validates data processing systems, BigQuery analytics, Dataflow pipelines, Pub/Sub event streams, and scalable warehousing.",
            "official_url": "https://cloud.google.com/learn/certification/data-engineer",
            "prep_url": "https://www.cloudskillsboost.google/paths/16",
            "exam_guide_url": "https://cloud.google.com/learn/certification/guides/data-engineer"
        },
        {
            "id": "google-data-analytics",
            "title": "Google Data Analytics Professional Certificate",
            "issuer": "Coursera / Google",
            "level": "Beginner to Intermediate",
            "target_years": ["1st Year", "2nd Year", "3rd Year"],
            "domains": ["Data & Analytics", "Agile & Project Management"],
            "skills": ["SQL & Relational Querying", "Database Management Systems", "Mathematics & Statistics"],
            "skill_keys": ["SQL", "DBMS", "Math_Stats"],
            "vector": {"SQL": 1.0, "DBMS": 0.85, "Math_Stats": 0.75},
            "description": "Covers practical data wrangling, SQL calculations, Tableau visual storytelling, and statistical analysis for executive decision-making.",
            "official_url": "https://www.coursera.org/professional-certificates/google-data-analytics",
            "prep_url": "https://grow.google/certificates/data-analytics/",
            "exam_guide_url": "https://grow.google/certificates/data-analytics/"
        },
        {
            "id": "tf-dev-cert",
            "title": "TensorFlow Developer Certificate",
            "issuer": "DeepLearning.AI / Google",
            "level": "Intermediate to Advanced",
            "target_years": ["2nd Year", "3rd Year", "4th Year"],
            "domains": ["Artificial Intelligence", "Data & Analytics", "Software Engineering"],
            "skills": ["Machine Learning & AI", "Python Programming", "Mathematics & Statistics"],
            "skill_keys": ["ML_AI", "Python", "Math_Stats"],
            "vector": {"ML_AI": 1.0, "Python": 0.95, "Math_Stats": 0.75},
            "description": "Validates practical deep learning architectures, CNNs, NLP sequence models, model optimization, and production inference.",
            "official_url": "https://www.deeplearning.ai/courses/tensorflow-developer-professional-certificate/",
            "prep_url": "https://www.tensorflow.org/certificate",
            "exam_guide_url": "https://www.tensorflow.org/extras/surveys/candidate_handbook.pdf"
        },
        {
            "id": "ibm-ai-engineer",
            "title": "IBM AI Engineering Professional Certificate",
            "issuer": "edX / IBM",
            "level": "Intermediate",
            "target_years": ["2nd Year", "3rd Year", "4th Year"],
            "domains": ["Artificial Intelligence", "Data & Analytics"],
            "skills": ["Machine Learning & AI", "Python Programming", "Mathematics & Statistics"],
            "skill_keys": ["ML_AI", "Python", "Math_Stats"],
            "vector": {"ML_AI": 1.0, "Python": 0.85, "Math_Stats": 0.8},
            "description": "Comprehensive PyTorch, Scikit-Learn, computer vision, natural language transformers, and neural networks on edX.",
            "official_url": "https://www.edx.org/certificates/professional-certificate/ibm-ai-engineering",
            "prep_url": "https://www.edx.org/certificates/professional-certificate/ibm-ai-engineering",
            "exam_guide_url": "https://www.ibm.com/training/badge/ai-engineer"
        },
        {
            "id": "databricks-assoc-spark",
            "title": "Databricks Certified Associate Developer for Apache Spark",
            "issuer": "Databricks",
            "level": "Intermediate",
            "target_years": ["3rd Year", "4th Year"],
            "domains": ["Data & Analytics", "Database & Big Data", "Software Engineering"],
            "skills": ["Python Programming", "SQL & Relational Querying", "Database Management Systems"],
            "skill_keys": ["Python", "SQL", "DBMS"],
            "vector": {"Python": 0.9, "SQL": 0.9, "DBMS": 0.85},
            "description": "Assesses deep understanding of the Spark architecture, distributed partitions, and DataFrame manipulation at scale.",
            "official_url": "https://www.databricks.com/learn/certification/spark-developer-associate",
            "prep_url": "https://academy.databricks.com/",
            "exam_guide_url": "https://www.databricks.com/sites/default/files/2023-01/Databricks-Certified-Associate-Developer-for-Apache-Spark-3.0-Exam-Guide.pdf"
        },
        {
            "id": "cka-kubernetes",
            "title": "Certified Kubernetes Administrator (CKA)",
            "issuer": "The Linux Foundation / CNCF",
            "level": "Advanced",
            "target_years": ["3rd Year", "4th Year"],
            "domains": ["Cloud & DevOps", "Infrastructure & Networking", "Software Engineering"],
            "skills": ["Cloud Architecture & Docker", "OS & Computer Networks", "Cybersecurity Defense"],
            "skill_keys": ["CloudDocker", "OS_Networks", "Cybersecurity"],
            "vector": {"CloudDocker": 1.0, "OS_Networks": 0.85, "Cybersecurity": 0.65},
            "description": "Rigorous hands-on performance exam demonstrating mastery in Kubernetes cluster setup, overlay networking, storage, and pod scaling.",
            "official_url": "https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/",
            "prep_url": "https://training.linuxfoundation.org/training/kubernetes-fundamentals/",
            "exam_guide_url": "https://docs.linuxfoundation.org/tc-docs/certification/important-instructions-cka-ckad"
        },
        {
            "id": "comptia-sec-plus",
            "title": "CompTIA Security+ (SY0-701)",
            "issuer": "CompTIA",
            "level": "Intermediate",
            "target_years": ["2nd Year", "3rd Year", "4th Year"],
            "domains": ["Cybersecurity & Defense", "Infrastructure & Networking"],
            "skills": ["Cybersecurity Defense", "OS & Computer Networks"],
            "skill_keys": ["Cybersecurity", "OS_Networks"],
            "vector": {"Cybersecurity": 1.0, "OS_Networks": 0.85},
            "description": "Global benchmark in enterprise cyber posture, cryptography, incident response, network auditing, and zero trust architectures.",
            "official_url": "https://www.comptia.org/certifications/security",
            "prep_url": "https://www.comptia.org/training/certmaster-learn/security",
            "exam_guide_url": "https://www.comptia.org/training/resources/exam-objectives"
        },
        {
            "id": "cisco-ccna",
            "title": "Cisco Certified Network Associate (CCNA 200-301)",
            "issuer": "Cisco",
            "level": "Associate",
            "target_years": ["2nd Year", "3rd Year", "4th Year"],
            "domains": ["Infrastructure & Networking", "Cybersecurity & Defense", "Cloud & DevOps"],
            "skills": ["OS & Computer Networks", "Cybersecurity Defense", "Cloud Architecture & Docker"],
            "skill_keys": ["OS_Networks", "Cybersecurity", "CloudDocker"],
            "vector": {"OS_Networks": 1.0, "Cybersecurity": 0.65, "CloudDocker": 0.5},
            "description": "Validates foundational networking, IP routing protocols, security fundamentals, Cisco IOS configurations, and network automation.",
            "official_url": "https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/associate/ccna.html",
            "prep_url": "https://learningnetwork.cisco.com/s/ccna",
            "exam_guide_url": "https://learningcontent.cisco.com/documents/marketing/exam-topics/200-301-CCNA.pdf"
        },
        {
            "id": "pmi-csm",
            "title": "Certified ScrumMaster (CSM) / PMI-ACP",
            "issuer": "Scrum Alliance / PMI",
            "level": "Beginner to Intermediate",
            "target_years": ["2nd Year", "3rd Year", "4th Year"],
            "domains": ["Agile & Project Management", "Management & Consulting"],
            "skills": ["Software Engineering Principles", "Database Management Systems"],
            "skill_keys": ["SE_Principles", "DBMS"],
            "vector": {"SE_Principles": 1.0, "DBMS": 0.4},
            "description": "Demonstrates practical Agile iteration workflows, sprint backlogs, team facilitation, and Scrum project governance.",
            "official_url": "https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster",
            "prep_url": "https://www.pmi.org/certifications/agile-acp",
            "exam_guide_url": "https://www.scrumalliance.org/certifications/csm-certification"
        },
        {
            "id": "unity-programmer",
            "title": "Unity Certified Professional: Programmer",
            "issuer": "Unity Technologies",
            "level": "Intermediate to Advanced",
            "target_years": ["3rd Year", "4th Year"],
            "domains": ["Game Development & Graphics", "C++ & Systems", "Software Engineering"],
            "skills": ["Java / C++ Systems", "Mathematics & Statistics", "Object-Oriented Programming"],
            "skill_keys": ["Java_CPP", "Math_Stats", "OOP"],
            "vector": {"Java_CPP": 1.0, "Math_Stats": 0.85, "OOP": 0.75},
            "description": "Certifies core real-time 3D game physics, custom shaders, gameplay scripting, memory management, and Unity profiler tuning.",
            "official_url": "https://unity.com/products/unity-certifications/professional-programmer",
            "prep_url": "https://learn.unity.com/",
            "exam_guide_url": "https://unity.com/products/unity-certifications"
        },
        {
            "id": "autodesk-inventor",
            "title": "Autodesk Certified Professional (AutoCAD / Inventor)",
            "issuer": "Autodesk",
            "level": "Intermediate to Advanced",
            "target_years": ["2nd Year", "3rd Year", "4th Year"],
            "domains": ["CAD/CAM & Mechanical", "Engineering Architecture"],
            "skills": ["Mathematics & Statistics", "Software Engineering Principles"],
            "skill_keys": ["Math_Stats", "SE_Principles"],
            "vector": {"Math_Stats": 1.0, "SE_Principles": 0.65},
            "description": "Industry benchmark for parametric solid modeling, finite element analysis, 3D assembly drafting, and CNC manufacturing workflows.",
            "official_url": "https://www.autodesk.com/certification/all-certifications",
            "prep_url": "https://www.autodesk.com/certification/learn",
            "exam_guide_url": "https://www.autodesk.com/certification/all-certifications"
        },
        {
            "id": "google-ux-cert",
            "title": "Google UX Design Professional Certificate",
            "issuer": "Coursera / Google",
            "level": "Beginner to Intermediate",
            "target_years": ["1st Year", "2nd Year", "3rd Year", "4th Year"],
            "domains": ["UI/UX Design", "Web Development", "Product & Media"],
            "skills": ["Modern Web Stack", "Software Engineering Principles", "Mobile Development"],
            "skill_keys": ["WebStack", "SE_Principles", "MobileDev"],
            "vector": {"WebStack": 0.85, "SE_Principles": 0.75, "MobileDev": 0.65},
            "description": "End-to-end user experience design, rapid Figma prototyping, accessibility heuristics, persona modeling, and usability trials.",
            "official_url": "https://www.coursera.org/professional-certificates/google-ux-design",
            "prep_url": "https://grow.google/certificates/ux-design/",
            "exam_guide_url": "https://grow.google/certificates/ux-design/"
        }
    ]


CERTIFICATION_CATALOG = load_certification_catalog()

# Long-form display names for benchmark skills, shared by skill gaps, narration and the learning pathway
SKILL_LABELS = {
    "DSA": "Data Structures & Algorithms",
    "OOP": "Object-Oriented Programming",
    "DBMS": "Database Management Systems",
    "OS_Networks": "OS & Computer Networks",
    "SE_Principles": "Software Engineering Principles",
    "Math_Stats": "Mathematics & Statistics",
    "Python": "Python Programming",
    "Java_CPP": "Java / C++ Systems",
    "SQL": "SQL & Relational Querying",
    "WebStack": "Modern Web Stack",
    "CloudDocker": "Cloud Architecture & Docker",
    "ML_AI": "Machine Learning & AI",
    "MobileDev": "Mobile Development",
    "Cybersecurity": "Cybersecurity Defense",
}

ALL_PEOPLE_SKILLS = [
    "Communicating & Articulating",
    "Team Leadership & Delegation",
    "Negotiation & Persuasion",
    "Client Facing & Presentation",
    "Mentoring & Teaching",
    "Active Listening & Empathy",
]

ALL_IDEAS_SKILLS = [
    "Problem Solving & Logic",
    "Creative & Visual Design",
    "Research & Investigation",
    "Storytelling & Conceptualizing",
    "Innovation & Prototyping",
    "Technical & Content Writing",
]

ALL_DATA_SKILLS = [
    "Analytical & Critical Thinking",
    "Detail-Oriented & Precision",
    "Planning & Task Organizing",
    "Time & Deadline Management",
    "Quantitative & Mathematical",
    "Monitoring & Evaluation",
]

ALL_EXEC_SKILLS = [
    "Hardware & System Troubleshooting",
    "Hands-on Prototyping",
    "Debugging & Root-Cause Analysis",
    "Working Under Pressure / Incidents",
    "Process Optimization",
    "Process & Protocol Adherence",
]

ALL_24_SOFT_SKILLS = ALL_PEOPLE_SKILLS + ALL_IDEAS_SKILLS + ALL_DATA_SKILLS + ALL_EXEC_SKILLS
